### ISSUE TITLE
Multiple entries with one file open

### ISSUE THREAD

**Issue by Rulqu** [viczem/ansible-keepass#1]
Would it be possible to get multiple entries without opening the keepass file multiple times? Currently it is time consuming when many entries get fetched during one playbook.

**Comment by Rulqu** [comment]
I tried with something like
```python
                                                                                                 
        for t in terms[0]:
            entry_path = t.get('path').strip('/')                                                                    
            entry_attr = t.get('variable') 
            # entry getting code here
```
And using something like 
```yml
keepass_dict:
  - username:
    path: 'path/to/entry'
    variable: 'username'
  - password:
    path: 'path/to/entry'
    variable: 'password'
  - become:
    path: 'path/to/entry' 
    variable: password

ansible_user: "{{ lookup('keepass',keepass_dict)}}"
```
This lacks the yml side of handling the returning array or dict, whichever is gonna be returned.
This seems to work but it would change the original purpose of the file too much so it would perhaps need to be and option somehow. My knowledge of python is lacking to do it the right way.
