### ISSUE TITLE
Implementation as cache plugin

### ISSUE THREAD

**Issue by LecrisUT** [viczem/ansible-keepass#43]
There can potentially be some hiccups if in the task lists you have two lookups of the same attachment with more than the `ttl` of the socket in between. In those cases the path variable still points to the temp file location, but in the meantime the database might have been closed, deleting the file.

Alternatively, maybe the attachment lookup can be coupled to a cache plugin so that we can expire it when the database is closed. I am not sure if we can have more than one cache plugin, but there seem to be plugins like `aws_ec2`, which I would suspect only target specific variables.

**Comment by viczem** [comment]
You can set the `ttl` to `0` and close socket when you need by `lookup('viczem.keepass.keepass', 'close')`

**Comment by LecrisUT** [comment]
That is not ideal because I want to make my playbooks and roles portable to share it with colleagues and only have the keepass integration on the inventory.

**Comment by viczem** [comment]
What you think about using the module `viczem.keepass.attachment`? You can remove an attachment file by `ansible.builtin.file` when needed.

**Comment by LecrisUT** [comment]
This would still not be able to be used within the inventory and would not make it as portable

**Comment by viczem** [comment]
Could you give more information why using the `viczem.keepass.attachment` module is not a solution?

**Comment by LecrisUT** [comment]
Here's an example setup:
Me an my colleague have different clusters with different inventory setups like:
```yaml
# Personal inventory that uses keepass
# /host_vars/my_host_A.yaml
secret_CA_root_key: "{{ lookup('viczem.keepass.keepass', 'Root CA', 'attachments', 'CA_key) }}"
```
```yaml
# Colleague inventory that doesn't use keepass
# /host_vars/colleague_host_Z.yaml
secret_CA_root_key: /local/path/to/CA/key
```
But we are both working on the same repo with a gitignore
```
# .gitignore
/host_vars
/group_vars
/inventory.yaml
```
Using the same roles and playbooks
```yaml
# /our_role/tasks/main.yaml
- name: Sign some certificate
  community.crypto.x509_certificate:
    provider: ownca
    ownca_privatekey_path: "{{ secret_CA_root_key }}"
```
```yaml
# /our_playbook.yaml
- name: Do some stuff
  hosts: common_group_name
  role:
    - our_role
```

In this setup we are not imposing a specific format/plugins/etc. on each other and we can both work on the same roles/playbooks etc.
